### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'patch'**

### ISSUE THREAD

**Issue by krishnarastogi** [sharif-apu/MID-DRAN#3]
**Traceback (most recent call last):
  File "main.py", line 11, in <module>
    options = mainParser(sys.argv[1:])
  File "/media/krishna/Data/Remidio/MID-DRAN/utilities/parserUtils.py", line 38, in mainParser
    if options.patch and (not (options.sourceDir and options.resultDir)):
AttributeError: 'Namespace' object has no attribute 'patch'**

Please define options.patch in the parserUtils.py

**Comment by sharif-apu** [comment]
Hi there!
We initially planned for extracting image patches with options.patch. Regrettebly, most of the existing medical images are already available in a smaller dimension. Therefore, we changed our plan and trained our model with full-size images. According to the current implementation and description, we may not require options.patch for training/testing our MID-DRAN. However, for mitigating ambiguity, I am removing that option for parserUtils.py and closing this issue.
